// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_read_hancock_bin(input : SEXP)->SEXP{

 let input_ : String = unwrapr!( String::rnew(input) );
 let res  = unwrapr!( read_hancock_bin(input_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

