// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_read_hancock_bin(SEXP input);
SEXP MyFirstRust_read_hancock_bin(SEXP input){ return(rustr_read_hancock_bin(input));}
