# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_cpp <- function(vec) {
    .Call('_HancockBinReader_sum_cpp', PACKAGE = 'HancockBinReader', vec)
}

cpp_add_one <- function(vec) {
    .Call('_HancockBinReader_cpp_add_one', PACKAGE = 'HancockBinReader', vec)
}

